version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Puerto para el panel de control de rabbitMQ
      - "5672:5672"  # Puerto para la comunicación con RabbitMQ
    
    environment:
      RABBITMQ_DEFAULT_USER: ivrogo
      RABBITMQ_DEFAULT_PASS: root